### PR TITLE
Add dependencies required to compile on Debian to README file

### PR DESCRIPTION
**Pull request by franzcor**
Hello. 
With this PR I am adding the required Dependencies in the README install section to install Miracle-WM on Debian.
Previously you needed to check them in the CMake file manually.
Please tell me if there is any change to make in order to make this PR accepted!

### CODE REVIEW

**Comment by mattkae** [comment]
Whoops! This got automatically closed... because I purged a file from the repo @franzcor :sweat_smile: Do you think that you could reopen?

Also, I have been AFK all weekend, so was going to look at this today :)

**Comment by franzcor** [comment]
I cannot reopen. If I try to create a new PR it brings me to this page too..

**Comment by mattkae** [comment]
@franzcor Kk, I can reopen it today :+1: That's what I get for doing weird git things...

**Comment by mattkae** [comment]
Hiya @franzcor : Just opened a PR for this https://github.com/mattkae/miracle-wm/pull/91. Let me know if you want to take a look at it

**Pull request closed without merging**
